- index.js
- package.json
- spec/fetch.spec.js
npm supports referencing git repos on "well-known" hosts with a syntax like `github:user/repo` or `bitbucket:user/repo`. Cordova-fetch currently fails to handle these references because they aren't detected by the `is-url` module.
This pulls in the same `hosted-git-info` module that npm uses to properly detect and support those references.
> Support git shortlink package references

- index.js
- package.json
- spec/fetch.spec.js
Currently Cordova returns a 501 for git+http fetching.  This enables the ability to reference git+http.  It would be nice if this could be applied to Cordova 7, since we aren't moving to 8 yet.  It definitely needs to be in 8 since nofetch is no longer supported.  (I assume it's just a matter of updating the package.json dependency in cordova-lib?)
Also, I tried writing a test for this.  However the unit tests are actually more like functional tests and hitting real endpoints.  I don't have a git+http endpoint to test with that isn't GitHub (the GitHub one is picked up by the hostedGitInfo logic).  So, I tested with my internal one that was the root of this problem.  I'll post the code here and you can decide how to integrate it into a test (perhaps mocking is in order).  This is part of …
> Enabling support for git+http

- index.js
- spec/fetch.spec.js
- spec/support/dummy-local-plugin/package.json
- spec/support/dummy-local-plugin/plugin.xml
https://issues.apache.org/jira/browse/CB-13503
This PR fixes a bug that prevents cordova-fetch from installing plugins when using a local path in package.json, using the syntax :
```
"dependencies": {
"my-plugin": "file:path/to/plugin",
…
}
```
the syntax without **file:** works but as [the JIRA issue says](https://issues.apache.org/jira/browse/CB-13503), the **file:** prefix is added when running _cordova platform add_, making subsequent runs fail.
This PR also adds a test case with a dummy plugin that gets installed twice, in order to trigger the problematic call to trimID.
> CB-13503 fix trimID bug when using file:path/to/plugin

- index.js
- spec/fetch-unit.spec.js
This commit ensures that all exported functions still return a Q instance but ensures that only native Promise interface methods are used. Removing Q is only a 3 line diff after applying this change and #16.
> Isolate Q usage to prepare later removal

- spec/fetch.spec.js
I just doubled timeouts until it worked on my local machine. Will merge this myself, just wanted watching people to be notified of this.
The real problem is that we are cloning 50MB worth of git repos over the network in some tests. If #18 should make it, we could speed this up a lot by including some bare-repo fixtures.
> Increase test timeouts to reduce spurious failures

- index.js
- package.json
- spec/fetch-unit.spec.js
This replaces the whole existing logic to determine the path of an installed package with a new one.
With this PR, we transparently support **all** spec formats that npm supports too.
Instead of a lot of guessing we just read the output of npm. Granted, parsing output that's intended for humans isn't perfect either, but I tried a lot of things and this is the only thing that get's the job done reliably and without a big performance impact.
There's still a few things that could be improved with this, but I wanted to get this out ASAP to get some feedback, especially I'd like to know whether you find this approach feasible. So consider this a proof of concept.
This supports all npm versions down to 3 (which are all that were bundled with node versions we support). The only possibly breaking …
> Simplify installation location retrieval

- package.json
- eslint@4 devDep update
- in-range eslint-* devDep updates
**Testing:**
**For discussion:**
Use eslint@5 with other major eslint-* updates, which would need eslint-config-standard@next until eslint-config-standard@12 is published ref: <https://github.com/standard/eslint-config-standard/issues/123>
> eslint devDep updates

- index.js
- package.json
- spec/fetch-unit.spec.js
- spec/fetch.spec.js
Resolves #43.
~This needs tests at the moment.~ Tests added.
> Look for node_modules in any recursive parent directory

- index.js
- spec/fetch-unit.spec.js
Previously, when NODE_PATH had a trailing separator like `/foo:/bar:`, resolving a module would hang indefinitely when the module was not found. This PR fixes that.
The bug was introduced in #44.
> Handle broken NODE_PATH setups gracefully

- .gitignore
- package.json
- spec/coverage.json
This PR is simply adding new command `npm run cover` as in cordova-ios, cordova-common and etc.
No changes in module itself.
The result of this command is as follows,
```
$ npm run cover
...
> nyc jasmine --config=spec/coverage.json
Started
.................
17 specs, 0 failures
Finished in 88.889 seconds
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |    86.89 |    66.67 |    88.89 |    86.89 |                   |
index.js |    86.89 |    66.67 |    88.89 |    86.89 |... 08,121,146,163 |
----------|----------|----------|----------|----------|-------------------|
```
> Add test coverage command in package.json

- package.json
- spec/fetch.spec.js
It appears that Jasmine 3.3.0 works here, although we might want to pin it to `~3.1.0` just for consistency
> dependency updates (cordova-common@3, etc.)

- index.js
- spec/fetch-unit.spec.js
**What does this PR do?**
------------------------------------------
Fix issue #59, where in Nightly in the `getTargetPackageSpecFromNpmInstallOutput` method, if the dependency or sub-dependency have a postinstall, for example electron package, it will print out extra lines.
```
> electron@3.1.1 postinstall /cordova-project/node_modules/electron
> node install.js 
```
Because of this additional prinout, the `getTargetPackageSpecFromNpmInstallOutput` method fails to parse properly the printout for the package name.
------------------------------------------
------------------------------------------
Loop throught the npm install output and look for the particular format that contains the package name.
------------------------------------------
------------------------------------------ …
> Properly detect npm install package name

- package.json
Current version of `nyc` is bugged for `node >= 10`.
This PR updates the `nyc` dev dependency to the latest released version. The new version also continues to support `node >= 6` which fits current master.
- `npm t`
> chore: update nyc dev dependency

- spec/fetch.spec.js
When using `npm@>=6.11.0` on Windows, `npm uninstall` of `cordova-android@5.1.1` will leave an empty folder `node_modules/cordova-android/node_modules` behind. This causes one of our tests to fail but it is very likely an issue with npm. Furthermore this is very unlikely to affect users of `cordova-fetch` in production.
We just install a later version of `cordova-android` and `cordova-ios` in the test. The exact version or even package installed does not really matter, the test just asserts that a package can be installed and then uninstalled .
CI tests are passing again.
> Work around npm bug when uninstalling old cordova platforms

- package.json
Update the third-party production npm dependencies to ensure that our package remains vulnerability free that can come from third-party dependencies.
Enables us to use new features, leverage speed improvements, and resolve issues that were caused by third-party dependency bugs.
Updated Dependencies
* fs-extra@^8.1.0
* npm-package-arg@^6.1.1
* resolve@^1.12.0
* semver@^6.3.0
- `npm t`
> chore: bump production dependencies

- index.js
- spec/fetch-unit.spec.js
- spec/fetch.spec.js
Save platforms and plugins to devDependencies and close #64.
For more details please refer to the #64 issue.
`npm t`
> Save platforms and plugins to devDependencies

- .eslintrc.yml
- .travis.yml
- package.json
- spec/.eslintrc.yml
- spec/fetch-unit.spec.js
- spec/fetch.spec.js
* replace eslint dependencies with @cordova/eslint-config
* update eslint config
* eslint corrections
- `npm t`
> refactor: eslint setup

- README.md
Just decided to move the badges under the header to remove the linter warning to a tool I am using to make sure format is consistent.
https://github.com/DavidAnson/markdownlint/blob/v0.19.0/doc/Rules.md#md041 
This layout is also being applied to all other repo.
> doc(README): fix markdown lint warning

- index.js
Although platform-specific paths usually work just fine, this is the way it should be (see https://nodejs.org/api/modules.html).
> fix: use POSIX-style paths for require.resolve & Co

- index.js
We use the package `resolve` to find out if a requested dependency is already installed. That package exports a callback based async API that we promisify using `pify`. Since the callback of `resolve` is called with multiple result arguments, we need to use the `multiArgs` option of `pify` here. Unfortunately that also wraps the errors of `resolve` into an array.
This PR unwraps the errors returned by our promisified `resolve`.
Manual
> fix: do not pack rejections from resolve in array

- index.js
Preparation of a potential fix for https://github.com/apache/cordova-lib/issues/859
Also: https://github.com/apache/cordova/issues/175
Use async/await where applicable
All automated tests still pass
> refactor: use async/await where applicable

- .github/workflows/ci.yml
- index.js
- package-lock.json
- package.json
- spec/fetch-unit.spec.js
- spec/fetch.spec.js
https://github.com/apache/cordova-lib/issues/859
Instead of parsing the installed package's name out of the output of `npm install <spec>` (which does not work anymore with `npm@7`) we now do the following:
- First try to determine the name from the spec using `npm-package-arg`. This is very cheap.
- If that fails, get out the big guns and fetch a full manifest using `pacote`.
Both of these libraries are also used by npm itself.
Fetching the manifest can be expensive (e.g. for a git repo spec). But since `pacote` and `npm` share a cache and we always install a package after fetching a manifest anyway, the additional cost should be negligible in our case. Measuring the execution time of this repo's tests on my machine seems to confirm this: the time is roughly the same before and after …
> fix: cordova-fetch with npm@7

- .github/workflows/ci.yml
test
Node.js 16 is the future LTS and providing npm@7 > 7.2 already.
Use of node 16.x to replace 15.x with custom npm@7 update from #91.
Local `npm cit` success on:
* OS: Windows 10
* Node: 16.0.0
* npm: 7.10.0
> ci: test with Node 16 instead of 15 for already correct version of npm@7

- .github/workflows/ci.yml
n/a
One of the Node 14 tests is failing because of a change in a sub package that seems to have an effect with npm 6.
Upgraded global npm to version ^7.2.
GitHub Actions
> ci(workflow): node 14 tests to use npm ^7.2

- .github/workflows/ci.yml
- package-lock.json
- package.json
n/a
Bump package requirements
- Drop Node 14 as it will reach EOL by April 2023
- Set Node Requirement to >= 16.0.0
- Set npm requirement to >= 7.10.0 (should be default that comes with node 16.0.0 installation)
- Update CI Workflow
n/a
> feat!: bump package requirement node>=16 & npm>=7.10

- index.js
- package-lock.json
- package.json
n/a
* Use latest `pacote` dependency.
* Remove deprecation warnings.
> npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
* Upgraded dependency `pacote` to `15.0.7`
* Added dependency `@npmcli/arborist`
* Resolve peer dependency which was a breaking change introduced in [14.0.0-pre.3](https://github.com/npm/pacote/blob/main/CHANGELOG.md# …
> dep(npm): update pacote to 15.0.7

- .github/workflows/ci.yml
n/a
Sync recent changes made in other repos around CodeCov Action
Similar changes were taken from [cordova-common repo](https://github.com/apache/cordova-common/blob/master/.github/workflows/ci.yml#L49-L53).
* Did not copy over the `name` field. 
* IMO GitHub Action's default name `Run codecov/codecov-action@v3` is sufficient. 
* Added the `if` field.
* Only run CodeCov when successful.
* Added the `with` → `name` field. 
* Improves CodeCov's Run Result Dashboard labeling. (Example: `4538518365` becomes `Linux node.js 18.x`)
* Dropped `fail_ci_if_error`.
* Try to prevent CI failures that might be caused by CodeCov. E.g. failures to upload results. 
Tested on external repo.
> ci: sync codecov-action setup between other repos

- .github/workflows/ci.yml
- index.js
- package-lock.json
- package.json
- spec/fetch.spec.js
- spec/helpers.js
* Added Node 20 to the CI testing matrix
* Updated some dependencies to the latest version
* Use built-in `fs` functions where possible, removing `fs-extra` as a dependency
* Existing test suite passes.
> chore(deps): Update some dependencies, add Node 20 to CI

- .github/workflows/ci.yml
Dependabot pushes a branch to the repo and opens a pull request. The pull request workflow runs properly, but the push workflow fails because dependabot doesn't have access to a read/write GITHUB_TOKEN and doesn't have access to the repo secrets.
The quick fix is telling CI not to run the push event workflow for branches that start with `dependabot/`.
> chore(ci): Fix dependabot code scanning errors

- .github/workflows/ci.yml
- package-lock.json
- package.json
n/a
node < 20 are already EOL.
- Upgrade node to 20.5.0
- Bump node modules:
- @npmcli/arborist
- cordova-common
- npm-package-arg
- pacote
- resolve
- semver
- which
- @cordova/eslint-config
- jasmine
- nyc
- Update packages by `npm update`
NOTE:
- `execa` could not be updated because it switched commonjs to esm from next version.
- `file-url` ould not be updated because it switched commonjs to esm from next version.
- `nyc` should be replaced with `c8` but separate from this PR.
- npm t
- npm run lint
> chore!: bump node requirement & npm dependencies
